### ISSUE TITLE
Installing package fails in Windows due to symlink error

### ISSUE THREAD

**Issue by Lev-Zabudko** [2do2go/npack#1]
Install process for my package fails in Windows (i'm using Win 10, starting from win 7 users able to use symlinks):
<npack> Move package to "D:\kk\packages\2016.04.14-11.22.47"
<npack> Switch to new package "2016.04.14-11.22.47"
<npack> Set package "2016.04.14-11.22.47" as current
<npack> Remove and create new symlink
<npack> Error: EPERM: operation not permitted, symlink 'packages\2016.04.14-11.22.47' -> 'D:\kk\package'

Maybe you could fix it for win? Here is some manual that explains how to make symlinks in windows.
http://lifehacker.com/5496652/how-to-use-symlinks-in-windows

thx.

**Comment by Lev-Zabudko** [comment]
OK, that was paroblem with admin rights, now all works fine)

**Comment by okv** [comment]
npack works on windows, nice to hear that =)
